### ISSUE TITLE
Need to kill then restart server after adding belongs_to :author

### ISSUE THREAD

**Issue by stazman** [learn-co-students/using-active-model-serializer-v-000#225]
Just a note: apparently I needed to restart the server after adding belongs_to :author to post_serializer.rb for the author's name to show up in the JSON. It was interesting to see how I needed to do the same thing for changing Active Record associations in Rails itself. You might want to add that to this lesson's text. Just sayin' :)

**Comment by drakeltheryuujin** [comment]
Hi @stazman,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
