### ISSUE TITLE
App still missing views folder and tests need to be fixed

### ISSUE THREAD

**Issue by arianaberger** [learn-co-students/using-active-model-serializer-v-000#270]
Post_spec.rb is has tests that require views, and there is no views folder. 
The readme doesn't mention whether we should be adding view pages to make the tests pass or not.

**Comment by bthooper** [comment]
I noticed the same issue. Failed to get it working...

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
