### ISSUE TITLE
Deprecated dependency issues

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-students/using-active-model-serializer-v-000#312]
"Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (~> 4.2) was resolved to 4.2.11.1, which depends on
      bundler (>= 1.3.0, < 2.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (>= 1.3.0, < 2.0)', which is required by gem 'rails (~> 4.2)', in
any of the sources.

Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    capybara was resolved to 3.16.1, which depends on
      ruby (>= 2.4.0)

    rails (~> 4.2) was resolved to 4.2.11.1, which depends on
      ruby (>= 1.9.3)"

**Comment by atxrenegade** [comment]
Previous lab required an upgrade to bundler 2.0 which is now breaking this one.

**Comment by drakeltheryuujin** [comment]
Hi @atxrenegade ,
I'm having difficulty reproducing the issue with `Bundler version 2.0.1`, so I'm going to close it for now.
It's possible it was remedied from another fix. If you do not believe that this issue has been addressed, please re-open this issue. As always, thanks for contributing! 💙
