### ISSUE TITLE
No spec/test files available in order for green light to light up in Learn lesson page

### ISSUE THREAD

**Issue by ivillicana** [learn-co-students/using-active-model-serializer-v-000#328]
Students are not able to submit this lab in the Learn lesson page, as it requires tests to be passed and submitted in order to continue. A workaround is creating generic tests by running `bundle exec rails g rspec:install`, then running `learn` and `learn submit`.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe this issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
