### ISSUE TITLE
views folder missing, also does AMS support Rails 5?

### ISSUE THREAD

**Issue by kevinYCKim33** [learn-co-students/using-active-model-serializer-v-000#64]
Please check the code under "we need to get rid of the to_json stuff...."  

It actually doesn't get rid of the to_json method.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
