### ISSUE TITLE
Replacing AMS with Fast JSON API

### ISSUE THREAD

**Issue by Mk-Etlinger** [learn-co-students/using-active-model-serializer-v-000#69]
Hi guys,

https://github.com/Netflix/fast_jsonapi
https://medium.com/netflix-techblog/fast-json-api-serialization-with-ruby-on-rails-7c06578ad17f

This could be an improvement to the curriculum in that `Fast JSON API` handles serializing up to 25 times faster than AMS.

It may not be as feature rich as AMS yet, but worth looking into and at the very least making a note about it in the lesson.

Cheers,

Mike

**Comment by jouissances** [comment]
As AMS is currently undergoing renovation, its documentation also offered us several [alternatives](https://github.com/rails-api/active_model_serializers#alternatives), which include **fast_jsonapi**.

**Comment by stazman** [comment]
Just a thought: Perhaps fast j_son (images of a huffing and puffing Jason Alexander come to mind for some reason) could be used for production code and AMS be used for development, interchangeably?

**Comment by drakeltheryuujin** [comment]
Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
